### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by andrewsource** [btcsuite/btcutil#104]
I install package using command `go get -u github.com/btcsuite/btcutil`. It returns error:

`# github.com/btcsuite/btcutil
btcsuite/btcutil/block.go:82: b.msgBlock.SerializeNoWitness undefined (type *wire.MsgBlock has no field or method SerializeNoWitness)
btcsuite/btcutil/tx.go:63: t.msgTx.WitnessHash undefined (type *wire.MsgTx has no field or method WitnessHash)
btcsuite/btcutil/tx.go:77: t.msgTx.HasWitness undefined (type *wire.MsgTx has no field or method HasWitness)
`

I using golang 1.8.3 (in both ubuntu 14.04 TS 32 bit and 64bit).

**Comment by davecgh** [comment]
This is because the PR that the most recent commits relied on had not yet been merged to master.  It has now been merged.
