### ISSUE TITLE
ExtendedKey need to add ChildNum method

### ISSUE THREAD

**Issue by w20089527** [btcsuite/btcutil#111]
childNum is not exported. And there is no exported method to retrieve it.

**Comment by onyb** [comment]
@w20089527 Fixed in #171. You can now access `childNum` with the `ChildIndex` method:

https://github.com/btcsuite/btcutil/blob/6065135ba824dc2b89d4da75699dcb2885bc3e2a/hdkeychain/extendedkey.go#L338-L341

**Comment by jcvernaleo** [comment]
fixed.
