### ISSUE TITLE
Is the algorithm testing the derived child point is at infinity right?

### ISSUE THREAD

**Issue by ruoshan** [btcsuite/btcutil#117]
https://github.com/btcsuite/btcutil/blob/06f32abe079c0670ea6adf08f41754ef36063a72/hdkeychain/extendedkey.go#L304

According to the BIP32, should we test the `childX` and `childY` instead of the above code?
I don't know much about the secp256k1 curve, I am  confused about how to testing whether or not the point is at finity, in `btcec` pkg, it's tested by `X.Sign() == 0 && Y.Sign() == 0`, but here, it's tested by `X.Sign() == 0 || Y.Sign() ==0`, why the OR logic not AND?

**Comment by Roasbeef** [comment]
The new version of this routine looks like: https://github.com/btcsuite/btcd/blob/master/btcutil/hdkeychain/extendedkey.go#L343
