### ISSUE TITLE
function to know the number of bitcoin mined at a given block number

### ISSUE THREAD

**Issue by frranck** [btcsuite/btcutil#123]
Hello,
Is there a function in this library to know the number of bitcoin mined at a given block number ?
Regards

**Comment by onyb** [comment]
@frranck You can use the [`getblockstats`](https://bitcoin.org/en/developer-reference#getblockstats) RPC command to get the subsidy (in satoshis) at the specified block height.

```sh
$ curl --user myuser:mypass --data '{"method":"getblockstats","params":[628768],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST "rpcServerURL"  | jq ".result.subsidy"
1250000000
```

**Comment by onyb** [comment]
@frranck I'm assuming from the 🚀 reaction that we can close this issue. 🙂
