### ISSUE TITLE
Decoding failure

### ISSUE THREAD

**Issue by husio** [btcsuite/btcutil#137]
I have noticed that decoding done with `bech32.Decode` returns different result than https://github.com/nym-zone/bech32

The below diff is adding a test that proves that 
```diff
diff --git a/bech32/bech32_test.go b/bech32/bech32_test.go
index 1322386..9583a1c 100644
--- a/bech32/bech32_test.go
+++ b/bech32/bech32_test.go
@@ -5,6 +5,8 @@
 package bech32_test
 
 import (
+       "bytes"
+       "encoding/hex"
        "strings"
        "testing"
 
@@ -67,3 +69,25 @@ func TestBech32(t *testing.T) {
                }
        }
 }
+
+func TestBench32Encoding(t *testing.T) {
+       // bech32  -e -h tiov 746573742d7061796c6f6164
+       const enc = `tiov1w3jhxapdwpshjmr0v9jqymqq4y`
+
+       want, err := hex.DecodeString("746573742d7061796c6f6164")
+       if err != nil {
+               t.Fatal(err)
+       }
+
+       _, payload, err := bech32.Decode(enc)
+       if err != nil {
+               t.Fatal(err)
+       }
+
+       if !bytes.Equal(want, payload) {
+               t.Logf("want %d", want)
+               t.Logf("got  %d", payload)
+               t.Fatal("invalid decode")
+       }
+
+}
```

**Comment by ethanfrey** [comment]
Looks like that library is a no-go for now. I was digging in to see if the bech32 c utility was reliable (or maybe that one had errors). Seems this uses code pulled from the reference implementation.

Digging for test vectors to validate one over the other, I found a [list of reference implementations](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#reference-implementations) in many languages, [including go](https://github.com/sipa/bech32/tree/master/ref/go). And this version includes a [complete test suite with test vectors](https://github.com/sipa/bech32/blob/master/ref/go/src/bech32/bech32_test.go).

Digging in, I found no license file, but as one github user [pointed out](https://github.com/sipa/bech32/issues/42), there is a [BSD license in the source itself](https://github.com/sipa/bech32/blob/master/ref/go/src/bech32/bech32.go#L1-L21).

Given this code has not changed in around 2 years and is a reference implementation, I would suggest copying these files (including the original copyright notice) into our repo and using that.

**Comment by husio** [comment]
I think I am missing bits conversion part. It all makes more sense when looking at the encoding example where the bits encoding is used as well https://github.com/btcsuite/btcutil/blob/master/bech32/example_test.go#L32-L49

**Comment by Roasbeef** [comment]
In your example, you aren't converting to base 5 before decoding.
