### ISSUE TITLE
Is fastReduction from gcs.go supposed to be equivalent to the modulo operation?

### ISSUE THREAD

**Issue by AlexITC** [btcsuite/btcutil#138]
From what I understand, the [fastReduction](https://github.com/btcsuite/btcutil/blob/master/gcs/gcs.go#L54) is supposed to be equivalent to the modulo operation, while experimenting, I found that it is not the case.

`fastReduction(6573390126540650161, 13343827) = 4754995` while `6573390126540650161 mod 13343827 = 438473`

**Comment by Roasbeef** [comment]
No they aren't meant to be _equivalent_, but they have a similar distribution, which is all we need for our use case.

**Comment by AlexITC** [comment]
That's what I noticed, as I read about GCS using modulo I was curious whether this was intentional.

Thanks.
