### ISSUE TITLE
Requesting New Release (v1.0.2 seems outdated)

### ISSUE THREAD

**Issue by Shachindra** [btcsuite/btcutil#193]
Using this package in my code gives this error:

`masterKey.Derive undefined (type *hdkeychain.ExtendedKey has no field or method Derive)`

Seems like go modules refer to https://pkg.go.dev/github.com/btcsuite/btcutil -> github.com/btcsuite/btcutil v1.0.2  which don't include the commits after Apr 14, 2020. Looks like I need to refer to the [commit: ](https://github.com/btcsuite/btcutil/commit/dde9e31e50c913f5fa56ff1e405dd442dd12e452) - hdkeychain: correct BIP-32 derivation issue on Oct 21, 2020 for my code to work properly.

 Any help on this matter would be appreciated.

**Comment by ashfame** [comment]
@Shachindra Did you update your locally installed package? Try running `go get -u github.com/btcsuite/btcutil` again

**Comment by Shachindra** [comment]
Yes @ashfame . I did it using ```go version go1.15.7 windows/amd64``` . So far this is what I found:

0. Error: 

![1 Derive](https://user-images.githubusercontent.com/5115199/106769313-d1588680-6662-11eb-991e-0c0d2603a153.png)

1. Running go get -u github.com/btcsuite/btcutil 

![2 GoGet](https://user-images.githubusercontent.com/5115199/106769366-e46b5680-6662-11eb-8d39-278cf4776190.png)

2. My ```go.mod``` file

![3 GoMod](https://user-images.githubusercontent.com/5115199/106769395-ecc39180-6662-11eb-9900-d18c8f82679c.png)

3. Clicking on the link points to https://pkg.go.dev/github.com/btcsuite/btcutil@v1.0.2 where the directory [hdkeychain](https://pkg.go.dev/github.com/btcsuite/btcutil@v1.0.2/hdkeychain) doesn't have function named 'Derive'.

Nevertheless, Maybe there is some issue in my go modules which is fetching the files from the older version of the package. I wanted to verify whether the error gets fixed if there is a new release. 
I (temporarily) fixed the error by copying the entire hdkeychain directory from [here](https://github.com/btcsuite/btcutil/tree/master/hdkeychain) locally into my repo. This seems to have fixed the error but I'll have to manually check for updates into the btcutil/hdkeychain/ repo.

I can always fork the repo and refer to that as a last resort.

**Comment by joshmh** [comment]
Agreed, a version bump would be helpful. The latest version isn't compatible with the latest PSBT format from Electrum and Specter. The parsing only worked when I fetched the latest commit.

**Comment by nkuba** [comment]
One more vote for a release.

**Comment by benma** [comment]
Please release a new version :pray:

**Comment by Roasbeef** [comment]
A new `v2` module exists in the new home for this repo (`btcd/btcutil`).
