### ISSUE TITLE
Support single-key P2TR output scripts and addresses

### ISSUE THREAD

**Issue by benma** [btcsuite/btcutil#200]
- One more instance of the Address interface
- v1 witness scripts to be supported in [DecodeAddress()](https://github.com/btcsuite/btcutil/blob/e2ba6805a89060647fa22ec61b799acff6a4f6fd/address.go#L130)
- a new function named `NewAddressTaprootPubkey()` or similar.

More details: https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki

Related to bech32m support: https://github.com/btcsuite/btcutil/issues/195

**Comment by benma** [comment]
Tracked also in https://github.com/btcsuite/btcd/issues/1735

**Comment by Roasbeef** [comment]
This is next now that #195 is in
