### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by ademcan** [btcsuite/btcutil#203]
Hey team, thanks for the amazing lib, I was wondering if there was any "getting started" tutorial somewhere. The only resource I could find online is the following: https://gobitcoinbook.org/

**Comment by guggero** [comment]
Hey Adem.
It depends on what your goals are. This is a pure library, nothing that can be executed on its own.
There are other projects like https://github.com/btcsuite/btcwallet (which [`lnd`](https://github.com/lightningnetwork/lnd) uses for its internal on-chain wallet) and https://github.com/btcsuite/btcd which depend on this library.
Those projects should have a bit more documentation on how to get started.

**Comment by ademcan** [comment]
Hey Oliver :) 
Got it, thanks for the clarification, will check the 2 libraries you mentioned!
Keep up the great work!
