### ISSUE TITLE
HD keys created from seeds are always instatiated with MainNet version

### ISSUE THREAD

**Issue by cjepson** [btcsuite/btcutil#65]
The NewMaster function only creates a new HD key with the MainNet version parameters. The function should alternatively take a network parameter as an argument and allows using other network parameters.

**Comment by davecgh** [comment]
You can set the network on the returned `*ExtendedKey` with the `SetNet` method, but I agree that it would be more intuitive and less error prone if he `NewMaster` function required the network to be specified.  I'll submit a PR making that change shortly.
