### ISSUE TITLE
Benchmarks for deriving child public keys from an extended pub key

### ISSUE THREAD

**Issue by mrkent** [btcsuite/btcutil#69]
Is it feasible to use a xpub to derive millions of child keys (for example, for the purpose of generating vanity keys)?

Alternatively, are there benchmarks published of the existing benchmark tests?

**Comment by davecgh** [comment]
Not sure how I missed this question, but I just now saw it.  I don't think there are any benchmarks published, but the code is based on btcec which is quite a bit faster than OpenSSL's implementation, so I don't believe there is any reason it couldn't be used that way.

**Comment by mrkent** [comment]
Thanks.
