### ISSUE TITLE
Getting the address from a TxOutput

### ISSUE THREAD

**Issue by FrozenPrincess** [btcsuite/btcutil#81]
Given an address, it's [easy to get the script ](https://github.com/btcsuite/btcutil/blob/68e5965458062d031a6e333b35c778ce464fb73f/address.go#L66) but for the life of me, I can't figure out how go the other way.

i.e. I have a [TxOut](https://github.com/btcsuite/btcd/blob/5e93b1664e4a57aa997b77c6e4a8a90b4c90dd98/wire/msgtx.go#L196) and get the [PkScript](https://github.com/btcsuite/btcd/blob/5e93b1664e4a57aa997b77c6e4a8a90b4c90dd98/wire/msgtx.go#L198) and want to convert that into an address. I realize not every PkScript is an address, but in my case I only care about pay-to-pubkey-hash outputs anyway

**Comment by jrick** [comment]
https://godoc.org/github.com/btcsuite/btcd/txscript#example-ExtractPkScriptAddrs

**Comment by FrozenPrincess** [comment]
Thank you!
