### ISSUE TITLE
Exported ExtendedKey

### ISSUE THREAD

**Issue by cpacia** [btcsuite/btcutil#99]
The ExtendedKey struct in the hdkeychain package has all private fields. This is a bit problematic as my use case requires using a custom chaincode. 

Would you accept a PR changing `newExtendedKey` to exported so that people can create custom extended keys outside the package?

**Comment by davecgh** [comment]
I don't have any objections to that.  I would ask that you update the comment accordingly to say something along the lines that it should only be used for custom applications and ordinarily callers should use `NewMaster`, `Child`, and `Neuter`.
